import TextColoring
print("If it just looks like a mess you need to:")
print('If your running this in VS Code open a new terminal, click on terminal, then type, "python [YOUR_PROGRAM_NAME].py" and then there!')
print('If your using anything else then VS Code, use Terminal and type "python [YOUR_PROGRAM_NAME].py" and it will show the colors \n \n \n')
TextColoring.MAKE_TEXT("Rainbow!!!", True, None)
TextColoring.MAKE_TEXT("Colored!!!", False, "Green")
TextColoring.MAKE_TEXT("It comes in 8 diffrent colors:", True, None)
TextColoring.MAKE_TEXT("   Black", False, "Black")
TextColoring.MAKE_TEXT("   Red", False, "Red")
TextColoring.MAKE_TEXT("   Green", False, "Green")
TextColoring.MAKE_TEXT("   Yellow", False, "Yellow")
TextColoring.MAKE_TEXT("   Blue", False, "Blue")
TextColoring.MAKE_TEXT("   Cyan", False, "Cyan")
TextColoring.MAKE_TEXT("   Purple", False, "Purple")
TextColoring.MAKE_TEXT("   White", False, "White")